## Goldstein-price function
## 2-dimension function

In [4]:
import numpy as np

In [23]:
def goldstein_price(x):
    x = np.atleast_2d(x)
    
    x1 = x[:,0]
    x2 = x[:,1]
    
    
    a1 = x1 + x2 + 1
    a2 = 19 - 14*x1+3*x1**2-14*x2+6*x1*x2+3*x2**2
    
    b1 = 2*x1-3*x2
    b2 = 18-32*x1+12*x1**2+48*x2-36*x1*x2+27*x2**2
    
    A = 1 + (a1**2)*a2
    B = 30 +(b1**2)*b2
    
    return (1+A)*(30+B)

## Schaffer function 2

In [24]:
def schaffer_2(x):
    x = np.atleast_2d(x)
    
    x1 = x[:,0]
    x2 = x[:,1]
    
    A = np.sin((x1**2-x2**2))**2 - 0.5
    B = 1 + 0.001*(x1**2+x2**2)
    
    return 0.5 + A/(B**2)

In [25]:
x = [[1,2],[3,4],[5,6]]

In [26]:
schaffer_2(x)

array([0.02467994, 0.43492577, 0.94414239])

## Schaffer function 4

In [29]:
def schaffer_4(x):
    x = np.atleast_2d(x)
    
    x1 = x[:,0]
    x2 = x[:,1]
    
    B = 1 + 0.001*(x1**2+x2**2)
    A = np.cos(np.sin(np.abs((x1**2-x2**2)))) - 0.5
    
    return 0.5 + A/(B**2)

In [30]:
schaffer_4(x)

array([0.98519501, 0.77777391, 0.53580865])

## Levy function dimension customizing possible

In [57]:
def levy(x,dim):
    x = np.array(x)
    x_list = []
    w_list = []
    for i in range(dim):
        
        x_list.append(x[:,i].reshape(x.shape[0],1))
        w_list.append((x_list[i]-1)/4+1)
    A = np.sin(np.pi * w_list[0]) ** 2
    
    c1 = (w_list[dim-1]-1)**2
    c2 = 1 + np.sin(2*np.pi*w_list[dim-1])
    C = c1 * c2
    
    B = 0
    for i in range(dim-1):
        b1 = (w_list[i]-1)**2
        b2 = 1+ 10 * (np.sin(np.pi * w_list[i] + 1))**2
        
        B = B + b1 * b2
    
    return A + B + C

In [58]:
x = [[1,2],[3,4],[5,6]]

In [59]:
levy(x,2)

array([[ 0.125     ],
       [ 1.97981645],
       [11.20573418]])

In [60]:
x_6d = [[1,2,3,4,5,6],[2,3,4,5,6,7]]

In [61]:
levy(x_6d,6)

array([[13.66230707],
       [29.76619322]])

## Sum of different Power function

In [62]:
def sumdifpow(x,dim):
    x = np.array(x)
    x_list = []
    w_list = []
    for i in range(dim):
        
        x_list.append(x[:,i].reshape(x.shape[0],1))
    
    result = 0
    for i in range(dim):
        result = result + np.abs(x_list[i]) ** (i+2)
        
    return result

In [63]:
x

[[1, 2], [3, 4], [5, 6]]

In [64]:
sumdifpow(x,2)

array([[  9],
       [ 73],
       [241]], dtype=int32)

## Trid function

In [72]:
def trid(x,dim):
    x = np.array(x)
    
    x_list = []
    for i in range(dim):
        x_list.append(x[:,i].reshape(x.shape[0],1))
        
    A = 0
    B = 0
    
    for i in range(dim):
        a = (x_list[i]-1)**2
        A = A + a
    
    for i in range(dim-1):
        b = x_list[i+1] * x_list[i] - 1
        B = B + b
        
    return A - B

In [73]:
x

[[1, 2], [3, 4], [5, 6]]

In [74]:
trid(x,2)

array([[ 0],
       [ 2],
       [12]])

## Zakharov function

In [75]:
def zakharov(x,dim):
    x = np.array(x)
    
    x_list = []
    for i in range(dim):
        x_list.append(x[:,i].reshape(x.shape[0],1))
    
    A = 0
    B = 0
    C = 0
    for i in range(dim):
        A = A + x_list[i]**2
        B = B + 0.5 * (i+1) * x_list[i]
    
    return A + B**2 + B**4
        
    
    

In [76]:
x

[[1, 2], [3, 4], [5, 6]]

In [77]:
zakharov(x,2)

array([[  50.3125],
       [ 970.3125],
       [5353.3125]])

In [78]:
x_1d = [[1]]

In [79]:
zakharov(x_1d,1)

array([[1.3125]])

## Michalewicz function

In [83]:
def michalewicz(x,dim):
    x = np.array(x)
    x_list = []
    m = 10
    for i in range(dim):
        x_list.append(x[:,i].reshape(x.shape[0],1))
    result = 0
    for i in range(dim):
        A = np.sin(x_list[i])
        B = np.sin((i+1)*x_list[i]**2/np.pi)**(2*m)
            
        result = result + A*B
            
    return result
        


In [84]:
x_m_test = [[2.20,1.57]]

In [85]:
michalewicz(x_m_test, 2)

array([[1.80114072]])

## Ackley function

In [5]:
import numpy as np

In [14]:
def ackley(x,dim):
    x = np.array(x)
    x_list = []
    for i in range(dim):
        x_list.append(x[:,i].reshape(x.shape[0],1))
    a = 20
    b = 0.2
    c = np.pi * 2
    
    squared_sum = 0
    cos = 0
    for i in range(dim):
        squared_sum = x_list[i] ** 2 + squared_sum
        cos = cos + np.cos(c*x_list[i])
        
    A = -a * np.exp(-b*np.sqrt(squared_sum/dim))
    B = -np.exp(cos/dim)
    C = a
    D = np.exp(1)
    result = A + B + C + D
    return result.reshape(result.shape[0],1)

In [15]:
x = [[0,0,0,0,0]]

In [16]:
ackley(x,5)

array([[4.4408921e-16]])

## Branin function

In [21]:
def branin(x):
    sigma = 0
    x = np.atleast_2d(x)
    
    x1 = x[:,0]
    x2 = x[:,1]
   
    a = 1
    b = 5.1/(4*np.pi**2)
    c = 5/np.pi
    r = 6
    s = 10
    t = 1/(8*np.pi)
    
    A = a * ((x2 - b*(x1**2) + c*x1 - r) **2)
    B = s * (1-t) * np.cos(x1)
    
    result = A + B + s
    
    return result.reshape(result.shape[0],1) + np.random.normal(0,sigma,result.shape[0]).reshape(result.shape[0],1)

In [22]:
branin([9.42478,2.475])

array([[0.39788736]])

In [6]:
np.array([9.42478,2.475])

array([9.42478, 2.475  ])

### Rosenbrock function

In [1]:
def rosenbrock(x,dim):
    sigma = 0
    
    x = np.array(x)
    x_list = []
    
    for i in range(dim):
        x_list.append(x[:,i].reshape(x.shape[0],1))
    
    total_sum = 0 
    for i in range(dim-1):
        a = 100 * (x_list[i+1] - x_list[i] **2) **2
        b = (x_list[i] - 1)**2
        
        total_sum = total_sum + (a+b)
        
    result = total_sum
    
    return result.reshape(result.shape[0],1) + np.random.normal(0,sigma,result.shape[0]).reshape(result.shape[0],1)
    

In [2]:
x_test = [[1,1,1],[1,1,1]]

In [5]:
rosenbrock(x_test,3)

array([[0.],
       [0.]])